namespace HIVBackend.Models.DBModuls;
public partial class QrySearchEpid
{
    public int PatientId { get; set; }
    public DateOnly? InputDate { get; set; }
    public string? FamilyName { get; set; }
    public string? FirstName { get; set; }
    public string? ThirdName { get; set; }
    public string? SexShort { get; set; }
    public DateOnly? BirthDate { get; set; }
    public string? RegionLong { get; set; }
    public int? RegtypeId { get; set; }
    public string? RegionLongFact { get; set; }
    public int? FactRegtypeId { get; set; }
    public string? CountryLong { get; set; }
    public string? CityName { get; set; }
    public string? LocationName { get; set; }
    public string? AddrInd { get; set; }
    public string? AddrStreet { get; set; }
    public string? AddrHouse { get; set; }
    public string? AddrExt { get; set; }
    public string? AddrFlat { get; set; }
    public DateOnly? RegOnDate { get; set; }
    public DateOnly? RegOffDate { get; set; }
    public string? RegOff { get; set; }
    public string? CheckPlaceLong { get; set; }
    public string? DiagnosisLong { get; set; }
    public DateOnly? DieDate { get; set; }
    public DateOnly? DieAidsDate { get; set; }
    public string? DieCourseShort { get; set; }
    public string? DieCourseLong { get; set; }
    public int? DethtypeId { get; set; }
    public string? CheckCourseLong { get; set; }
    public string? InfectCourseLong { get; set; }
    public string? ShowIllnessLong { get; set; }
    public DateOnly? StartDate { get; set; }
    public DateOnly? EndDate { get; set; }
    public string? IbResultShort { get; set; }
    public DateOnly? BlotDate { get; set; }
    public int? BlotNo { get; set; }
    public bool? First1 { get; set; }
    public bool? Last1 { get; set; }
    public DateOnly? Datetime1 { get; set; }
    public string? HospCourseLong { get; set; }
    public int? Age { get; set; }
    public string? CardNo { get; set; }
    public string? ArvtLong { get; set; }
    public string? CodeMkb10Long { get; set; }
    public DateOnly? TransfAreaDate { get; set; }
    public bool? FlgZamMedPart { get; set; }
    public bool? FlgHeadPhysician { get; set; }
    public DateOnly? TransfFederDate { get; set; }
    public DateOnly? UfsinDate { get; set; }
    public string? Aids12Long { get; set; }
    public string? Snils { get; set; }
    public string? UnrzFr { get; set; }
    public string? EpidDescr { get; set; }

    public DateOnly? DtMailReg { get; set; }
    public string? EduName { get; set; }
    public string? FamilyStatusName { get; set; }
    public string? EmploymentName { get; set; }
    public string? TransName { get; set; }
    public string? PlaceCheckName { get; set; }
    public string? SituationDetectName { get; set; }
    public string? TrasmisoinMechName { get; set; }
    public string? VulnerableGroupName { get; set; }
    public DateOnly? DVac1 { get; set; }
    public DateOnly? DVac2 { get; set; }
    public string? VacName { get; set; }
    public DateOnly? DPositivResCovid { get; set; }
    public DateOnly? DNegativeResCovid { get; set; }
    public string? Mkb10LongName { get; set; }
    public string? YnNameChemsex { get; set; }
    public string? ChemsexContactType { get; set; }
    public DateOnly? DateStartPavInj { get; set; }
    public DateOnly? DateEndPavInj { get; set; }
    public string? YnNamePavInj { get; set; }
    public DateOnly? DateStartPavNotInj { get; set; }
    public DateOnly? DateEndPavNotInj { get; set; }
    public string? YnNamePavNotInj { get; set; }
    public DateOnly? EpidemInfectStart { get; set; }
    public DateOnly? EpidemInfectEnd { get; set; }
    public string? Callstatus { get; set; }
    public DateOnly? CallDate { get; set; }
}

