namespace HIVBackend.Models.DBModuls;
public partial class QrySearchTreatment
{
    public int PatientId { get; set; }
    public DateOnly? InputDate { get; set; }
    public string? FamilyName { get; set; }
    public string? FirstName { get; set; }
    public string? ThirdName { get; set; }
    public string? SexShort { get; set; }
    public DateOnly? BirthDate { get; set; }
    public string? RegionLong { get; set; }
    public int? RegtypeId { get; set; }
    public string? RegionLongFact { get; set; }
    public int? FactRegtypeId { get; set; }
    public string? CountryLong { get; set; }
    public string? CityName { get; set; }
    public string? LocationName { get; set; }
    public string? AddrInd { get; set; }
    public string? AddrStreet { get; set; }
    public string? AddrHouse { get; set; }
    public string? AddrExt { get; set; }
    public string? AddrFlat { get; set; }
    public DateOnly? RegOnDate { get; set; }
    public DateOnly? RegOffDate { get; set; }
    public string? RegOff { get; set; }
    public string? DiagnosisLong { get; set; }
    public DateOnly? DieDate { get; set; }
    public DateOnly? DieAidsDate { get; set; }
    public string? DieCourseShort { get; set; }
    public string? DieCourseLong { get; set; }
    public int? DethtypeId { get; set; }
    public string? CheckCourseLong { get; set; }
    public string? InfectCourseLong { get; set; }
    public string? ShowIllnessLong { get; set; }
    public DateOnly? StartDate { get; set; }
    public DateOnly? EndDate { get; set; }
    public DateOnly? TransfAreaDate { get; set; }
    public bool? FlgZamMedPart { get; set; }
    public bool? FlgHeadPhysician { get; set; }
    public string? IbResultShort { get; set; }
    public DateOnly? BlotDate { get; set; }
    public int? BlotNo { get; set; }
    public bool? First1 { get; set; }
    public bool? Last1 { get; set; }
    public DateOnly? Datetime1 { get; set; }
    public DateOnly? UfsinDate { get; set; }
    public string? InvalidLong { get; set; }
    public string? CorrespIllnessLong { get; set; }
    public DateOnly? CorrespIllnessDate { get; set; }
    public string? CureSchemaLong { get; set; }
    public DateOnly? SchemaStartDate { get; set; }
    public bool? SchemaLast { get; set; }
    public string? MedforschemaLong { get; set; }
    public string? CureChangeLong { get; set; }
    public string? MedicineLong { get; set; }
    public string? GiveMedicineLong { get; set; }
    public string? DoctorLong { get; set; }
    public DateOnly? GiveDate { get; set; }
    public string? CardNo { get; set; }
    public string? FinSourceLong { get; set; }
    public string? ArvtLong { get; set; }
    public string? RangeTherapyLong { get; set; }
    public DateOnly? VlDate { get; set; }
    public int? VlResult { get; set; }
    public DateOnly? ImDate { get; set; }
    public int? ImResult { get; set; }

}

