namespace HIVBackend.Models.FormModels.Search
{
    public class SearchMainInfForm
    {
        public string dateInpStart { get; set; }
        public string dateInpEnd { get; set; }
        public string patientId { get; set; }
        public string familyName { get; set; }
        public string firstName { get; set; }
        public string thirdName { get; set; }
        public string fioChange { get; set; }
        public string sex { get; set; }
        public string birthDateStart { get; set; }
        public string birthDateEnd { get; set; }
        public string[]? regionReg { get; set; }
        public string[]? regionFact { get; set; }
        public string[]? country { get; set; }
        public string city { get; set; }
        public string location { get; set; }
        public string indx { get; set; }
        public string street { get; set; }
        public string home { get; set; }
        public string dateRegOnStart { get; set; }
        public string dateRegOnEnd { get; set; }
        public string dateUnRegStart { get; set; }
        public string dateUnRegEnd { get; set; }
        public string unRegCourse { get; set; }
        public string[]? blotCheckPlace { get; set; }
        public string[]? stage { get; set; }
        public string dateDieStart { get; set; }
        public string dateDieEnd { get; set; }
        public string dateDieAidsStart { get; set; }
        public string dateDieAidsEnd { get; set; }
        public string[]? checkCourse { get; set; }
        public string[]? dieCourse { get; set; }
        public string diePreset { get; set; }
        public string[]? infectCourse { get; set; }
        public string[]? showIllnes { get; set; }
        public string dateShowIllnesStart { get; set; }
        public string dateShowIllnesEnd { get; set; }
        public string ibRes { get; set; }
        public string dateIbResStart { get; set; }
        public string dateIbResEnd { get; set; }
        public string ibNum { get; set; }
        public string dateInpIbStart { get; set; }
        public string dateInpIbEnd { get; set; }
        public string ibSelect { get; set; }
        public string[]? hospCourse { get; set; }
        public string[]? age { get; set; }
        public string cardNo { get; set; }
        public string[]? art { get; set; }
        public string[]? mkb10 { get; set; }
        public string archiveYNA { get; set; }
        public string archive { get; set; }
        public string transfAreaYNA { get; set; }
        public string dateTransfAreaStart { get; set; }
        public string dateTransfAreaEnd { get; set; }
        public string frYNA { get; set; }
        public string zavApoYNA { get; set; }
        public string transfFederYNA { get; set; }
        public string dateTransfFederStart { get; set; }
        public string dateTransfFederEnd { get; set; }
        public string ufsinYNA { get; set; }
        public string dateUfsinStart { get; set; }
        public string dateUfsinEnd { get; set; }
        public string aids12 { get; set; }
        public string unrzYNA { get; set; }
        public string unrz { get; set; }
        public string dieDiagYNA { get; set; }
        public string chemprof { get; set; }
        public string dateChemprofStartStart { get; set; }
        public string dateChemprofStartEnd { get; set; }
        public string dateChemprofEndStart { get; set; }
        public string dateChemprofEndEnd { get; set; }
        public string dateRegStart { get; set; }
        public string dateRegEnd { get; set; }
        public string regionPreset { get; set; }
        public string factRegionPreset { get; set; }

        public bool selectInpDate { get; set; }
        public bool selectPatientId { get; set; }
        public bool selectFio { get; set; }
        public bool selectSex { get; set; }
        public bool selectBirthDate { get; set; }
        public bool selectRegion { get; set; }
        public bool selectRegionFact { get; set; }
        public bool selectCountry { get; set; }
        public bool selectAddr { get; set; }
        public bool selectRegOnDate { get; set; }
        public bool selectBlotCheckPlace { get; set; }
        public bool selectStage { get; set; }
        public bool selectDieDate { get; set; }
        public bool selectCheckCourse { get; set; }
        public bool selectDieCourse { get; set; }
        public bool selectInfectCourse { get; set; }
        public bool selectShowIllnes { get; set; }
        public bool selectIb { get; set; }
        public bool selectHospCourse { get; set; }
        public bool selectAge { get; set; }
        public bool selectCardNo { get; set; }
        public bool selectArt { get; set; }
        public bool selectMkb10 { get; set; }
        public bool selectArchive { get; set; }
        public bool selectTransfArea { get; set; }
        public bool selectFr { get; set; }
        public bool selectTransfFeder { get; set; }
        public bool selectUfsin { get; set; }
        public bool selectAids12 { get; set; }
        public bool selectUnrz { get; set; }
        public bool selectChemprof { get; set; }
        public bool selectDieDiag { get; set; }
        public bool selectDateReg { get; set; }
        public bool selectPasSer { get; set; }
        public bool selectPasNum { get; set; }
        public bool selectPasWhom { get; set; }
        public bool selectPasWhen { get; set; }

        public int Page { get; set; }
        public bool Excel { get; set; }
    }
}
